pragma tpch(1);
copy (from _) to 'queries/tpch/answers/sf1/q01.csv';
pragma tpch(2);
copy (from _) to 'queries/tpch/answers/sf1/q02.csv';
pragma tpch(3);
copy (from _) to 'queries/tpch/answers/sf1/q03.csv';
pragma tpch(4);
copy (from _) to 'queries/tpch/answers/sf1/q04.csv';
pragma tpch(5);
copy (from _) to 'queries/tpch/answers/sf1/q05.csv';
pragma tpch(6);
copy (from _) to 'queries/tpch/answers/sf1/q06.csv';
pragma tpch(7);
copy (from _) to 'queries/tpch/answers/sf1/q07.csv';
pragma tpch(8);
copy (from _) to 'queries/tpch/answers/sf1/q08.csv';
pragma tpch(9);
copy (from _) to 'queries/tpch/answers/sf1/q09.csv';
pragma tpch(10);
copy (from _) to 'queries/tpch/answers/sf1/q10.csv';
pragma tpch(11);
copy (from _) to 'queries/tpch/answers/sf1/q11.csv';
pragma tpch(12);
copy (from _) to 'queries/tpch/answers/sf1/q12.csv';
pragma tpch(13);
copy (from _) to 'queries/tpch/answers/sf1/q13.csv';
pragma tpch(14);
copy (from _) to 'queries/tpch/answers/sf1/q14.csv';
pragma tpch(15);
copy (from _) to 'queries/tpch/answers/sf1/q15.csv';
pragma tpch(16);
copy (from _) to 'queries/tpch/answers/sf1/q16.csv';
pragma tpch(17);
copy (from _) to 'queries/tpch/answers/sf1/q17.csv';
pragma tpch(18);
copy (from _) to 'queries/tpch/answers/sf1/q18.csv';
pragma tpch(19);
copy (from _) to 'queries/tpch/answers/sf1/q19.csv';
pragma tpch(20);
copy (from _) to 'queries/tpch/answers/sf1/q20.csv';
pragma tpch(21);
copy (from _) to 'queries/tpch/answers/sf1/q21.csv';
pragma tpch(22);
copy (from _) to 'queries/tpch/answers/sf1/q22.csv';